name: Publish interface package

on:
  push:
    branches: [ ]
  pull_request:
    branches: [ ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: "Build backsplice.spreadsheet"
      run: dotnet build --no-restore

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 7.0.x 
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          source-url: https://nuget.pkg.github.com/james-d-hasselman/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create the package
        run: dotnet pack --configuration Release --no-build

      - name: Publish the package to GitHub Packages registry
        run: dotnet nuget push src/Backsplice.Spreadsheet/bin/Release/*.nupkg -k ${{ secrets.GITHUB_TOKEN }}
